rjs_show_controls: false
rjs_progress_bar: true
rjs_slide_number: true
rjs_history: true
rjs_keyboard_shortcuts: true
rjs_slide_overview: true
rjs_vertical_centering: true
rjs_touch_navigation: true
rjs_loop: false
rjs_rtl: false
rjs_fragments: true
rjs_embedded: false
rjs_help: false
rjs_show_notes: false
rjs_auto_slide: 0
rjs_auto_slide_stoppable: true
rjs_mouse_wheel: false
rjs_hide_address_bar: true
rjs_preview_links: false
rjs_transition_style: "slide"
rjs_transition_speed: "default"
rjs_background_transition: "default"
rjs_view_distance: 3
rjs_parallax_background_image: ""
rjs_parallax_background_size: ""
rjs_parallax_background_horizontal: null
rjs_parallax_background_vertical: null
